#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

mkdir -p /var/log/sympa/sshd
chown nobody:nogroup /var/log/sympa/sshd

exec chpst -u nobody:nogroup svlogd -tt /var/log/sympa/sshd
