#!/bin/bash -e

# Sleep so that main Sympa process can start and prepare everything.
sleep 10

export FCGI_SOCKET_PATH="127.0.0.1:9000"

# All output is logged to /var/log/sympa/sympa.log so we redirect stdout and stderr to /dev/null.
exec chpst -u sympa:sympa /usr/lib/cgi-bin/sympa/wwsympa.fcgi >/dev/null 2>&1
