#!/bin/bash -e

# Sleep so that main Sympa process can start and prepare everything.
sleep 10

# All output is logged to /var/log/sympa/sympa.log so we redirect stdout and stderr to /dev/null.
exec chpst -u sympa:sympa /usr/local/sbin/bulk.pl --foreground >> /var/log/sympa.log 2>&1
