#!/bin/bash -e

if [ -n "$SET_REAL_IP_FROM" ]; then
  echo "set_real_ip_from $SET_REAL_IP_FROM;" > /etc/nginx/conf.d/set_real_ip_from.conf
else
  rm -f /etc/nginx/conf.d/set_real_ip_from.conf
fi

# Initialization hook.
[ -f /etc/service/nginx/run.initialization ] && source /etc/service/nginx/run.initialization

exec /usr/sbin/nginx -g "daemon off;" 2>&1
